### ISSUE TITLE
Dict comprehension not working

### ISSUE THREAD

**Issue by arashsoheili** [AndreiRegiani/falcon-jsonify#2]
I'm trying to take a sqlalchemy result row proxy as dict comprehension and I'm getting this error
```
typeError: '{"public_hash": "b092c948679dd3f877ff4f83aca54f889db96eca", "first_name": "Jerry",   "state": "FL", "province": null, "zipcode": "33437-3741", "country_code": null}' is not a byte
```
My dict comprehension is as follows:
`resp.json = {c: result[c] for c in result.keys()}`

It seem any string actually gives this same error. I'm on Python 3.6.1 on MacOs

**Comment by arashsoheili** [comment]
On process_response need to use resp.body instead of resp.data since that's bytes. I tested and it works in both python 2 and python 3.
```
    def process_response(self, req, resp, resource, req_succeeded):
        try:
            resp.body = json.dumps(resp.json)
        except AttributeError:
            pass```

**Comment by AndreiRegiani** [comment]
Thanks @arashsoheili!

It's now fixed, commit: https://github.com/AndreiRegiani/falcon-jsonify/commit/4a95976adc74dcc453dfcedcce06c092376d9b90

Soon will be updated on pip (`falcon-jsonify` package).
