### ISSUE TITLE
JSON response

### ISSUE THREAD

**Issue by joseasv** [AndreiRegiani/falcon-jsonify#3]
Hello there. I'm getting this error 

`
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/falconexample/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/home/vagrant/.virtualenvs/falconexample/lib/python3.4/site-packages/gunicorn/http/wsgi.py", line 343, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: '{"id": 6}' is not a byte
`

when trying to return a very simple JSON response like this
`resp.json = {"id" : data_object.id}`

I can get JSON encoded requests just fine. I know Gunicorn is raising the TypeError but I'm following the example given in the readme.

**Comment by Tethik** [comment]
Getting the same error if I add a print in process_response. I think the issue is that the author is calling
```
resp.data = json.dumps(resp.json)
```
which in python3 (which I'm using) won't work because json.dumps returns a string and resp.data expects bytes.

**Comment by AndreiRegiani** [comment]
Fixed by @Tethik 
Merged and released on pip 
`pip3 install falcon-jsonify`
(https://pypi.python.org/pypi/falcon-jsonify)
